#spring:
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092
#
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: test
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json
      kafka:
        binder:
          brokers: localhost:9092