#spring:
#  cloud:
#    stream:
#      kafka:
#        binder:
#          brokers: localhost:9092
#
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input: # channel name
          destination: test # topic
          contentType: application/json
          group: myGroup # consumer groups
          consumer:
            startOffset: "latest"
            concurrency: 3

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081